---

- hosts: webservers

  remote_user: root
  gather_facts: False
  serial: 1

  pre_tasks:
    - name: "Disable {{ servername }}"
      delegate_to: localhost
      netscaler_server:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        disabled: yes

        name: "{{ servername }}"
        ipaddress: "{{ hostip }}"

  post_tasks:

    - name: "Re enable {{ servername }}"
      delegate_to: localhost
      netscaler_server:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        name: "{{ servername }}"
        ipaddress: "{{ hostip }}"

  tasks:

    - name: "Update {{ servername }}"
      delegate_to: localhost
      command: docker-compose exec -d "{{ servername }}" bash -c "echo 'hello updated {{ servername }}' > /app/content.txt"
