- hosts: webservers

  gather_facts: False

  tasks:
    - name: "Update {{ servername }}"
      delegate_to: localhost
      command: docker-compose exec -d "{{ servername }}" bash -c "echo 'hello {{ servername }}' > /app/content.txt"

- hosts: netscaler
  gather_facts: no
  tasks:
    - name: Setup server 1
      delegate_to: localhost
      netscaler_server:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        state: present

        name: webapp1
        ipaddress: 172.30.0.21

    - name: Setup server 2
      delegate_to: localhost
      netscaler_server:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        state: present

        name: webapp2
        ipaddress: 172.30.0.22

    - name: Setup service 1
      delegate_to: localhost
      netscaler_service:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        state: present

        name: service_1
        servicetype: HTTP
        servername: webapp1
        port: 8000

    - name: Setup service 2
      delegate_to: localhost
      netscaler_service:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        state: present

        name: service_2
        servicetype: HTTP
        servername: webapp2
        port: 8000

    - name: Setup lb vserver
      delegate_to: localhost
      netscaler_lb_vserver:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        state: present

        name: lb_vserver_1
        lbmethod: ROUNDROBIN
        servicetype: HTTP
        ipv46: 172.30.0.200
        port: 8000
        servicebindings:
          - servicename: service_1
            weight: 50
          - servicename: service_2
            weight: 50
